### ISSUE TITLE
misc/jokes bug in "random_choice"

### ISSUE THREAD

**Issue by juposs** [juposs/python#5]
Traceback (most recent call last):
  File "./jokes", line 127, in <module>
    text = random_choice()
  File "./jokes", line 124, in random_choice
    text = random_joke + "\n\n" + random_quote
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Seemingly randomly appears

**Comment by juposs** [comment]
Fixed now - see commit
https://github.com/juposs/python/commit/d77079cc2dde2665c12ca690021ef0d0d7a62a83
